import type { PropId } from '../types/ids';
import { PALETTE as C } from './palette';
import type { Palette, SpriteSource } from './sprite';

export interface PropArt {
  source: SpriteSource;
  palette: Palette;
}

const TREE: SpriteSource = {
  rows: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.....oooooo.....',
    '...ooLLLlllloo..',
    '..oLLlllllllllo.',
    '.oLLllllllllldo.',
    '.oLlllllllllldo.',
    'olllllllllllldo.',
    'olllllllllllldo.',
    'olllllllllllddo.',
    '.olllllllllldo..',
    '.olllllllllddo..',
    '..olllllllddo...',
    '...oolllddoo....',
    '.....oottoo.....',
    '......otto......',
    '.....ottTo......',
    '.....otTo.......',
    '.....otTo.......',
    '......ottTo.....',
    '......otTTo.....',
    '.......otTo.....',
    '.......ottTo....',
    '......ottTTo....',
    '.....ootttTTo...',
    '....ooottTTooo..',
    '...ssssssssss...',
  ],
};

const PUMPKIN: SpriteSource = {
  rows: [
    '................',
    '................',
    '................',
    '........ss......',
    '.......ss.......',
    '...ooooossoooo..',
    '..oppPppppPpppo.',
    '.oppPppppppPpppo',
    '.opPpffppffpPppo',
    '.opPpffppffpPppo',
    '.opPppppppppPppo',
    '.opPpfppppfpPppo',
    '.opPppffffppPppo',
    '.oppPppppppPpppo',
    '..oppPppppPpppo.',
    '...oooooooooo...',
  ],
};

const LANTERN: SpriteSource = {
  rows: [
    '................',
    '................',
    '................',
    '................',
    '......oooo......',
    '.....oLLLLo.....',
    '.....oiyyio.....',
    '.....oiyYio.....',
    '.....oiyyio.....',
    '.....oiiiio.....',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '......oiio......',
    '.....oiiiio.....',
    '....oiiiiiio....',
    '....oooooooo....',
    '...ssssssssss...',
    '................',
  ],
};

const GRAVESTONE: SpriteSource = {
  rows: [
    '................',
    '................',
    '.....oooooo.....',
    '....oAAaaaao....',
    '...oAaaaaaaao...',
    '...oAaaakaaao...',
    '...oAaakkkaao...',
    '...oAaaakaaao...',
    '...oAaaakaaao...',
    '...oAaaaaaaao...',
    '...oAaaaaaaao...',
    '...oaaaaaaaao...',
    '...oaaaaaaaao...',
    '..oooooooooooo..',
    '..ssssssssssss..',
    '................',
  ],
};

const FENCE: SpriteSource = {
  rows: [
    '................',
    '................',
    '................',
    '..i...i...i...i.',
    '.iii.iii.iii.iii',
    '..i...i...i...i.',
    'iiiiiiiiiiiiiiii',
    '..i...i...i...i.',
    '..i...i...i...i.',
    '..i...i...i...i.',
    '..i...i...i...i.',
    'iiiiiiiiiiiiiiii',
    '..i...i...i...i.',
    '..i...i...i...i.',
    'ssssssssssssssss',
    '................',
  ],
};

/** A fence running up the screen, seen end-on: one post per tile on a rail that joins them. */
const FENCE_POST: SpriteSource = {
  rows: [
    '.......i........',
    '......iii.......',
    '.......i........',
    '.......is.......',
    '.......is.......',
    '......iiis......',
    '.......is.......',
    '.......is.......',
    '.......is.......',
    '.......is.......',
    '......iiis......',
    '.......is.......',
    '.......is.......',
    '.......is.......',
    '.......is.......',
    '.......is.......',
  ],
};

const WELL: SpriteSource = {
  rows: [
    '................................',
    '................................',
    '................................',
    '................................',
    '...........oooooooooo...........',
    '.........oRRrRRRRrRRRRo.........',
    '.......oRRRrRRRRrRRRRrRRo.......',
    '.....oRRRRrRRRRrRRRRrRRRRro.....',
    '...orRRRRrRRRRrRRRRrRRRRrRRRo...',
    '...oooooooooooooooooooooooooo...',
    '......ow.......nn.......wo......',
    '......ow.......nn.......wo......',
    '......ow.......nn.......wo......',
    '......ow.......nn.......wo......',
    '......ow.......nn.......wo......',
    '......ow......obbo......wo......',
    '......ow......obbo......wo......',
    '......ow......oooo......wo......',
    '......ow................wo......',
    '......ow................wo......',
    '...oooooooooooooooooooooooooo...',
    '...oAAaaAAaaAAaaAAaaAAaaAAaao...',
    '...ovvvvvvvvvvvvvvvvvvvvvvvvo...',
    '...ovvvvvvvvvvvvvvvvvvvvvvvvo...',
    '...okaaaaaaakaaaaaaakaaaaaaao...',
    '...oaaaakaaaaaaakaaaaaaakaaao...',
    '...okkkkkkkkkkkkkkkkkkkkkkkko...',
    '...oaaaakaaaaaaakaaaaaaakaaao...',
    '...okkkkkkkkkkkkkkkkkkkkkkkko...',
    '...oaaaakaaaaaaakaaaaaaakaaao...',
    '...oooooooooooooooooooooooooo...',
    '....ssssssssssssssssssssssss....',
  ],
};

/** One grid, three buildings: the roof and walls are palette keys, so each house is a recolour. */
const HOUSE: SpriteSource = {
  rows: [
    '................................................',
    '................................................',
    '................................................',
    '.................................oooooo.........',
    '.................................oCCCCo.........',
    '.................................occcco.........',
    '...............ooooooooooooooooooocccco.........',
    '..............oRRRRRRRRRRRRRRRRRRocccco.........',
    '.............orRRRrRRRrRRRrRRRrRRRoccco.........',
    '............oRRRRRrRRRRRrRRRRRrRRRRocco.........',
    '...........oRRRRRRRRRRRRRRRRRRRRRRRRoco.........',
    '..........orRRRrRRRrRRRrRRRrRRRrRRRrRoo.........',
    '.........oRRrRRRRRrRRRRRrRRRRRrRRRRRrRo.........',
    '........oRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRo........',
    '.......orRRRrRRRrRRRrRRRrRRRrRRRrRRRrRRRo.......',
    '......oRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRo......',
    '.....oRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRo.....',
    '....orRRRrRRRrRRRrRRRrRRRrRRRrRRRrRRRrRRRrRo....',
    '...oRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRo...',
    '..oRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRo..',
    '..oRRRrRRRrRRRrRRRrRRRrRRRrRRRrRRRrRRRrRRRrRRo..',
    '..oRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRRRRrRRo..',
    '..oRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRo..',
    '..orRRRrRRRrRRRrRRRrRRRrRRRrRRRrRRRrRRRrRRRrRo..',
    '.oooooooooooooooooooooooooooooooooooooooooooooo.',
    '....oWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwo....',
    '....oWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwo....',
    '....oWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwo....',
    '....oWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwo....',
    '....oWWWooooooooWWWWWWWWWWWWWWWWooooooooWWwo....',
    '....oWWWoYyooYyoWWWWWWWWWWWWWWWWoYyooYyoWWwo....',
    '....oWWWoyyooyyoWWWWWWWWWWWWWWWWoyyooyyoWWwo....',
    '....oWWWooooooooWWWWWooooooWWWWWooooooooWWwo....',
    '....oWWWoyyooyyoWWWWodDDDDdoWWWWoyyooyyoWWwo....',
    '....oWWWoyyooyyoWWWWodDDDDdoWWWWoyyooyyoWWwo....',
    '....oWWWoyyooyyoWWWWodDDDDdoWWWWoyyooyyoWWwo....',
    '....oWWWooooooooWWWWodDDDDdoWWWWooooooooWWwo....',
    '....oWWooooooooooWWWodDDDDdoWWWooooooooooWwo....',
    '....oWWofbfbfbfboWWWodDDDDdoWWWofbfbfbfboWwo....',
    '....oWWWWWWWWWWWWWWWodDDDkdoWWWWWWWWWWWWWWwo....',
    '....oWWWWWWWWWWWWWWWodDDDDdoWWWWWWWWWWWWWWwo....',
    '....oWWWWWWWWWWWWWWWodDDDDdoWWWWWWWWWWWWWWwo....',
    '....oWWWWWWWWWWWWWWWodDDDDdoWWWWWWWWWWWWWWwo....',
    '....oWWWWWWWWWWWWWWWodDDDDdoWWWWWWWWWWWWWWwo....',
    '....owwwwwwwwwwwwwwwodDDDDdowwwwwwwwwwwwwwwo....',
    '....owwwwwwwwwwwwwwwodDDDDdowwwwwwwwwwwwwwwo....',
    '...sssssssssssssssoaaaaaaaaaaosssssssssssssss...',
    '.....ssssssssssssssssssssssssssssssssssssss.....',
  ],
};

const SHADOW = C.mossDark;

function housePalette(roof: string, roofLight: string, wall: string, wallShade: string): Palette {
  return {
    '.': null,
    o: C.ink,
    R: roof,
    r: roofLight,
    W: wall,
    w: wallShade,
    c: C.stone,
    C: C.stoneLight,
    D: C.bark,
    d: C.barkDark,
    k: C.candle,
    y: C.candle,
    Y: C.candleBright,
    f: C.rose,
    b: C.hedgeLight,
    a: C.stone,
    s: SHADOW,
  };
}

export const PROP_ART: Record<PropId, PropArt> = {
  tree: {
    source: TREE,
    palette: {
      '.': null,
      o: C.ink,
      l: C.canopy,
      L: C.canopyLight,
      d: C.canopyDark,
      t: C.bark,
      T: C.barkDark,
      s: SHADOW,
    },
  },
  pumpkin: {
    source: PUMPKIN,
    palette: {
      '.': null,
      o: C.pumpkinDark,
      p: C.pumpkin,
      P: C.pumpkinLight,
      s: C.moss,
      f: C.candle,
    },
  },
  lantern: {
    source: LANTERN,
    palette: {
      '.': null,
      o: C.ink,
      L: C.iron,
      i: C.iron,
      y: C.candle,
      Y: C.candleBright,
      s: SHADOW,
    },
  },
  gravestone: {
    source: GRAVESTONE,
    palette: {
      '.': null,
      o: C.ink,
      a: C.stone,
      A: C.stoneLight,
      k: C.stoneDark,
      s: SHADOW,
    },
  },
  fence: { source: FENCE, palette: { '.': null, i: C.iron, s: SHADOW } },
  fencePost: { source: FENCE_POST, palette: { '.': null, i: C.iron, s: SHADOW } },
  well: {
    source: WELL,
    palette: {
      '.': null,
      o: C.ink,
      R: C.berry,
      r: C.berryLight,
      w: C.bark,
      n: C.rope,
      b: C.wood,
      a: C.stone,
      A: C.stoneLight,
      k: C.stoneDark,
      v: C.night,
      s: SHADOW,
    },
  },
  homeHouse: { source: HOUSE, palette: housePalette(C.plum, C.plumLight, C.cream, C.creamShade) },
  shopHouse: { source: HOUSE, palette: housePalette(C.teal, C.tealLight, C.cream, C.creamShade) },
  salonHouse: { source: HOUSE, palette: housePalette(C.rose, C.roseLight, C.ghost, C.creamShade) },
};
